services:
  mysql:
    image: mysql:latest
    container_name: mysql-sql-wac
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
     - bookstore
    restart: unless-stopped

  mail_dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  bookstore:
    driver: bridge

volumes:
  mysql-data: {}

